Replace some functions with executable scripts
These functions don't need to alter my environment. Furthermore, I don't
want to have to re-source a file every time I alter these. I'd also like
to have them in my $PATH so that all programs can access them.

diff --git a/Executables/shell-scripts/bin/new-executable b/Executables/shell-scripts/bin/new-executable
--- a/Executables/shell-scripts/bin/new-executable
+++ b/Executables/shell-scripts/bin/new-executable
@@ -1,7 +1,11 @@
 #!/usr/bin/env dash
 # vi:ft=sh
 newfile="$HOME/Executables/shell-scripts/bin/$1"
+[ -e "$newfile" ] && echo "error: file exists" 1>&2 && exit 1
 printf '#!/usr/bin/env dash\n\n# vi:ft=sh' >"$newfile"
 chmod +x "$newfile"
-# shellcheck source=/home/rkumar/startup.sh
+# shellcheck disable=SC2154
 $EDITOR "$newfile"
+if [ "$2" = '-g' ]; then
+	yadm add "$newfile"
+fi
